//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceWebClientProject.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        private System.DateTime DateofbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Dateofb {
            get {
                return this.DateofbField;
            }
            set {
                if ((this.DateofbField.Equals(value) != true)) {
                    this.DateofbField = value;
                    this.RaisePropertyChanged("Dateofb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private double AltitudeField;
        
        private WebServiceWebClientProject.ServiceReference1.AltitudeReference AltitudeReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((this.AltitudeField.Equals(value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public WebServiceWebClientProject.ServiceReference1.AltitudeReference AltitudeReference {
            get {
                return this.AltitudeReferenceField;
            }
            set {
                if ((this.AltitudeReferenceField.Equals(value) != true)) {
                    this.AltitudeReferenceField = value;
                    this.RaisePropertyChanged("AltitudeReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltitudeReference", Namespace="http://tempuri.org/")]
    public enum AltitudeReference : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ground = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ellipsoid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SeaLevel = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Surface = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.EmployeeWebServiceSoap")]
    public interface EmployeeWebServiceSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GentEmployeeDbResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GentEmployeeDb", ReplyAction="*")]
        WebServiceWebClientProject.ServiceReference1.GentEmployeeDbResponse GentEmployeeDb(WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GentEmployeeDb", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GentEmployeeDbResponse> GentEmployeeDbAsync(WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRadomNumber", ReplyAction="*")]
        int GetRadomNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRadomNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetRadomNumberAsync();
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetRandomsResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandoms", ReplyAction="*")]
        WebServiceWebClientProject.ServiceReference1.GetRandomsResponse GetRandoms(WebServiceWebClientProject.ServiceReference1.GetRandomsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandoms", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GetRandomsResponse> GetRandomsAsync(WebServiceWebClientProject.ServiceReference1.GetRandomsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetTrainLocation", ReplyAction="*")]
        void SetTrainLocation(double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetTrainLocation", ReplyAction="*")]
        System.Threading.Tasks.Task SetTrainLocationAsync(double latitude, double longitude);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetTrainLocationsResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrainLocations", ReplyAction="*")]
        WebServiceWebClientProject.ServiceReference1.GetTrainLocationsResponse GetTrainLocations(WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrainLocations", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GetTrainLocationsResponse> GetTrainLocationsAsync(WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetRadomLocationResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRadomLocation", ReplyAction="*")]
        WebServiceWebClientProject.ServiceReference1.GetRadomLocationResponse GetRadomLocation(WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRadomLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GetRadomLocationResponse> GetRadomLocationAsync(WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GentEmployeeDbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GentEmployeeDb", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequestBody Body;
        
        public GentEmployeeDbRequest() {
        }
        
        public GentEmployeeDbRequest(WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GentEmployeeDbRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GentEmployeeDbRequestBody() {
        }
        
        public GentEmployeeDbRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GentEmployeeDbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GentEmployeeDbResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceWebClientProject.ServiceReference1.GentEmployeeDbResponseBody Body;
        
        public GentEmployeeDbResponse() {
        }
        
        public GentEmployeeDbResponse(WebServiceWebClientProject.ServiceReference1.GentEmployeeDbResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GentEmployeeDbResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceWebClientProject.ServiceReference1.Employee GentEmployeeDbResult;
        
        public GentEmployeeDbResponseBody() {
        }
        
        public GentEmployeeDbResponseBody(WebServiceWebClientProject.ServiceReference1.Employee GentEmployeeDbResult) {
            this.GentEmployeeDbResult = GentEmployeeDbResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandoms", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceWebClientProject.ServiceReference1.GetRandomsRequestBody Body;
        
        public GetRandomsRequest() {
        }
        
        public GetRandomsRequest(WebServiceWebClientProject.ServiceReference1.GetRandomsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRandomsRequestBody {
        
        public GetRandomsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandomsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceWebClientProject.ServiceReference1.GetRandomsResponseBody Body;
        
        public GetRandomsResponse() {
        }
        
        public GetRandomsResponse(WebServiceWebClientProject.ServiceReference1.GetRandomsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRandomsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceWebClientProject.ServiceReference1.ArrayOfString GetRandomsResult;
        
        public GetRandomsResponseBody() {
        }
        
        public GetRandomsResponseBody(WebServiceWebClientProject.ServiceReference1.ArrayOfString GetRandomsResult) {
            this.GetRandomsResult = GetRandomsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTrainLocationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTrainLocations", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequestBody Body;
        
        public GetTrainLocationsRequest() {
        }
        
        public GetTrainLocationsRequest(WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTrainLocationsRequestBody {
        
        public GetTrainLocationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTrainLocationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTrainLocationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceWebClientProject.ServiceReference1.GetTrainLocationsResponseBody Body;
        
        public GetTrainLocationsResponse() {
        }
        
        public GetTrainLocationsResponse(WebServiceWebClientProject.ServiceReference1.GetTrainLocationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTrainLocationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceWebClientProject.ServiceReference1.Location[] GetTrainLocationsResult;
        
        public GetTrainLocationsResponseBody() {
        }
        
        public GetTrainLocationsResponseBody(WebServiceWebClientProject.ServiceReference1.Location[] GetTrainLocationsResult) {
            this.GetTrainLocationsResult = GetTrainLocationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRadomLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRadomLocation", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequestBody Body;
        
        public GetRadomLocationRequest() {
        }
        
        public GetRadomLocationRequest(WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRadomLocationRequestBody {
        
        public GetRadomLocationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRadomLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRadomLocationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceWebClientProject.ServiceReference1.GetRadomLocationResponseBody Body;
        
        public GetRadomLocationResponse() {
        }
        
        public GetRadomLocationResponse(WebServiceWebClientProject.ServiceReference1.GetRadomLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRadomLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceWebClientProject.ServiceReference1.Location GetRadomLocationResult;
        
        public GetRadomLocationResponseBody() {
        }
        
        public GetRadomLocationResponseBody(WebServiceWebClientProject.ServiceReference1.Location GetRadomLocationResult) {
            this.GetRadomLocationResult = GetRadomLocationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeWebServiceSoapChannel : WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeWebServiceSoapClient : System.ServiceModel.ClientBase<WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap>, WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap {
        
        public EmployeeWebServiceSoapClient() {
        }
        
        public EmployeeWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceWebClientProject.ServiceReference1.GentEmployeeDbResponse WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap.GentEmployeeDb(WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequest request) {
            return base.Channel.GentEmployeeDb(request);
        }
        
        public WebServiceWebClientProject.ServiceReference1.Employee GentEmployeeDb(int id) {
            WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequest inValue = new WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequest();
            inValue.Body = new WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequestBody();
            inValue.Body.id = id;
            WebServiceWebClientProject.ServiceReference1.GentEmployeeDbResponse retVal = ((WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap)(this)).GentEmployeeDb(inValue);
            return retVal.Body.GentEmployeeDbResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GentEmployeeDbResponse> WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap.GentEmployeeDbAsync(WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequest request) {
            return base.Channel.GentEmployeeDbAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GentEmployeeDbResponse> GentEmployeeDbAsync(int id) {
            WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequest inValue = new WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequest();
            inValue.Body = new WebServiceWebClientProject.ServiceReference1.GentEmployeeDbRequestBody();
            inValue.Body.id = id;
            return ((WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap)(this)).GentEmployeeDbAsync(inValue);
        }
        
        public int GetRadomNumber() {
            return base.Channel.GetRadomNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetRadomNumberAsync() {
            return base.Channel.GetRadomNumberAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceWebClientProject.ServiceReference1.GetRandomsResponse WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap.GetRandoms(WebServiceWebClientProject.ServiceReference1.GetRandomsRequest request) {
            return base.Channel.GetRandoms(request);
        }
        
        public WebServiceWebClientProject.ServiceReference1.ArrayOfString GetRandoms() {
            WebServiceWebClientProject.ServiceReference1.GetRandomsRequest inValue = new WebServiceWebClientProject.ServiceReference1.GetRandomsRequest();
            inValue.Body = new WebServiceWebClientProject.ServiceReference1.GetRandomsRequestBody();
            WebServiceWebClientProject.ServiceReference1.GetRandomsResponse retVal = ((WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap)(this)).GetRandoms(inValue);
            return retVal.Body.GetRandomsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GetRandomsResponse> WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap.GetRandomsAsync(WebServiceWebClientProject.ServiceReference1.GetRandomsRequest request) {
            return base.Channel.GetRandomsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GetRandomsResponse> GetRandomsAsync() {
            WebServiceWebClientProject.ServiceReference1.GetRandomsRequest inValue = new WebServiceWebClientProject.ServiceReference1.GetRandomsRequest();
            inValue.Body = new WebServiceWebClientProject.ServiceReference1.GetRandomsRequestBody();
            return ((WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap)(this)).GetRandomsAsync(inValue);
        }
        
        public void SetTrainLocation(double latitude, double longitude) {
            base.Channel.SetTrainLocation(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task SetTrainLocationAsync(double latitude, double longitude) {
            return base.Channel.SetTrainLocationAsync(latitude, longitude);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceWebClientProject.ServiceReference1.GetTrainLocationsResponse WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap.GetTrainLocations(WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequest request) {
            return base.Channel.GetTrainLocations(request);
        }
        
        public WebServiceWebClientProject.ServiceReference1.Location[] GetTrainLocations() {
            WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequest inValue = new WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequest();
            inValue.Body = new WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequestBody();
            WebServiceWebClientProject.ServiceReference1.GetTrainLocationsResponse retVal = ((WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap)(this)).GetTrainLocations(inValue);
            return retVal.Body.GetTrainLocationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GetTrainLocationsResponse> WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap.GetTrainLocationsAsync(WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequest request) {
            return base.Channel.GetTrainLocationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GetTrainLocationsResponse> GetTrainLocationsAsync() {
            WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequest inValue = new WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequest();
            inValue.Body = new WebServiceWebClientProject.ServiceReference1.GetTrainLocationsRequestBody();
            return ((WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap)(this)).GetTrainLocationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceWebClientProject.ServiceReference1.GetRadomLocationResponse WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap.GetRadomLocation(WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequest request) {
            return base.Channel.GetRadomLocation(request);
        }
        
        public WebServiceWebClientProject.ServiceReference1.Location GetRadomLocation() {
            WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequest inValue = new WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequest();
            inValue.Body = new WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequestBody();
            WebServiceWebClientProject.ServiceReference1.GetRadomLocationResponse retVal = ((WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap)(this)).GetRadomLocation(inValue);
            return retVal.Body.GetRadomLocationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GetRadomLocationResponse> WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap.GetRadomLocationAsync(WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequest request) {
            return base.Channel.GetRadomLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceWebClientProject.ServiceReference1.GetRadomLocationResponse> GetRadomLocationAsync() {
            WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequest inValue = new WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequest();
            inValue.Body = new WebServiceWebClientProject.ServiceReference1.GetRadomLocationRequestBody();
            return ((WebServiceWebClientProject.ServiceReference1.EmployeeWebServiceSoap)(this)).GetRadomLocationAsync(inValue);
        }
    }
}
