//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiduleServoceWebClient.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/BiduleService.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BiduleServoceWebClient.ServiceReference.FullTimeEmployee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BiduleServoceWebClient.ServiceReference.PartTimeEmployee))]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateofbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiduleServoceWebClient.ServiceReference.EmployeeType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dateofb {
            get {
                return this.DateofbField;
            }
            set {
                if ((this.DateofbField.Equals(value) != true)) {
                    this.DateofbField = value;
                    this.RaisePropertyChanged("Dateofb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiduleServoceWebClient.ServiceReference.EmployeeType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullTimeEmployee", Namespace="http://schemas.datacontract.org/2004/07/BiduleService.Models")]
    [System.SerializableAttribute()]
    public partial class FullTimeEmployee : BiduleServoceWebClient.ServiceReference.Employee {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnnualSalaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnnualSalary {
            get {
                return this.AnnualSalaryField;
            }
            set {
                if ((this.AnnualSalaryField.Equals(value) != true)) {
                    this.AnnualSalaryField = value;
                    this.RaisePropertyChanged("AnnualSalary");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartTimeEmployee", Namespace="http://schemas.datacontract.org/2004/07/BiduleService.Models")]
    [System.SerializableAttribute()]
    public partial class PartTimeEmployee : BiduleServoceWebClient.ServiceReference.Employee {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HourlyPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HoursWorkedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HourlyPay {
            get {
                return this.HourlyPayField;
            }
            set {
                if ((this.HourlyPayField.Equals(value) != true)) {
                    this.HourlyPayField = value;
                    this.RaisePropertyChanged("HourlyPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HoursWorked {
            get {
                return this.HoursWorkedField;
            }
            set {
                if ((this.HoursWorkedField.Equals(value) != true)) {
                    this.HoursWorkedField = value;
                    this.RaisePropertyChanged("HoursWorked");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeType", Namespace="http://schemas.datacontract.org/2004/07/BiduleService.Models")]
    public enum EmployeeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullTimeEmployee = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartTimeEmployee = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZeroFault", Namespace="http://schemas.datacontract.org/2004/07/BiduleService.Exceptions")]
    [System.SerializableAttribute()]
    public partial class ZeroFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/BiduleService")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientEmployee", Namespace="http://schemas.datacontract.org/2004/07/BiduleService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BiduleServoceWebClient.ServiceReference.FullTimeClientEmployee))]
    public partial class ClientEmployee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateofbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiduleServoceWebClient.ServiceReference.EmployeeClientType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dateofb {
            get {
                return this.DateofbField;
            }
            set {
                if ((this.DateofbField.Equals(value) != true)) {
                    this.DateofbField = value;
                    this.RaisePropertyChanged("Dateofb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiduleServoceWebClient.ServiceReference.EmployeeClientType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullTimeClientEmployee", Namespace="http://schemas.datacontract.org/2004/07/BiduleService")]
    [System.SerializableAttribute()]
    public partial class FullTimeClientEmployee : BiduleServoceWebClient.ServiceReference.ClientEmployee {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnnualSalaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnnualSalary {
            get {
                return this.AnnualSalaryField;
            }
            set {
                if ((this.AnnualSalaryField.Equals(value) != true)) {
                    this.AnnualSalaryField = value;
                    this.RaisePropertyChanged("AnnualSalary");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeClientType", Namespace="http://schemas.datacontract.org/2004/07/BiduleService")]
    public enum EmployeeClientType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullTimeClientEmployee = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartTimeClientEmployee = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IBiduleService")]
    public interface IBiduleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetEmployeeDB", ReplyAction="http://tempuri.org/IBiduleService/GetEmployeeDBResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BiduleServoceWebClient.ServiceReference.ZeroFault), Action="http://tempuri.org/IBiduleService/GetEmployeeDBZeroFaultFault", Name="ZeroFault", Namespace="http://schemas.datacontract.org/2004/07/BiduleService.Exceptions")]
        BiduleServoceWebClient.ServiceReference.Employee GetEmployeeDB(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetEmployeeDB", ReplyAction="http://tempuri.org/IBiduleService/GetEmployeeDBResponse")]
        System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.Employee> GetEmployeeDBAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/SaveEmployee", ReplyAction="http://tempuri.org/IBiduleService/SaveEmployeeResponse")]
        void SaveEmployee(BiduleServoceWebClient.ServiceReference.Employee Employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/SaveEmployee", ReplyAction="http://tempuri.org/IBiduleService/SaveEmployeeResponse")]
        System.Threading.Tasks.Task SaveEmployeeAsync(BiduleServoceWebClient.ServiceReference.Employee Employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetEmployee", ReplyAction="http://tempuri.org/IBiduleService/GetEmployeeResponse")]
        BiduleServoceWebClient.ServiceReference.Employee[] GetEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetEmployee", ReplyAction="http://tempuri.org/IBiduleService/GetEmployeeResponse")]
        System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.Employee[]> GetEmployeeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetFullTimeEmployee", ReplyAction="http://tempuri.org/IBiduleService/GetFullTimeEmployeeResponse")]
        BiduleServoceWebClient.ServiceReference.Employee GetFullTimeEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetFullTimeEmployee", ReplyAction="http://tempuri.org/IBiduleService/GetFullTimeEmployeeResponse")]
        System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.Employee> GetFullTimeEmployeeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetPartTimeEmployee", ReplyAction="http://tempuri.org/IBiduleService/GetPartTimeEmployeeResponse")]
        BiduleServoceWebClient.ServiceReference.Employee GetPartTimeEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetPartTimeEmployee", ReplyAction="http://tempuri.org/IBiduleService/GetPartTimeEmployeeResponse")]
        System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.Employee> GetPartTimeEmployeeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetMessage", ReplyAction="http://tempuri.org/IBiduleService/GetMessageResponse")]
        string GetMessage(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetMessage", ReplyAction="http://tempuri.org/IBiduleService/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetClients", ReplyAction="http://tempuri.org/IBiduleService/GetClientsResponse")]
        BiduleServoceWebClient.ServiceReference.Client[] GetClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetClients", ReplyAction="http://tempuri.org/IBiduleService/GetClientsResponse")]
        System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.Client[]> GetClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetEmployeeClient", ReplyAction="http://tempuri.org/IBiduleService/GetEmployeeClientResponse")]
        BiduleServoceWebClient.ServiceReference.FullTimeClientEmployee GetEmployeeClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiduleService/GetEmployeeClient", ReplyAction="http://tempuri.org/IBiduleService/GetEmployeeClientResponse")]
        System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.FullTimeClientEmployee> GetEmployeeClientAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBiduleServiceChannel : BiduleServoceWebClient.ServiceReference.IBiduleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiduleServiceClient : System.ServiceModel.ClientBase<BiduleServoceWebClient.ServiceReference.IBiduleService>, BiduleServoceWebClient.ServiceReference.IBiduleService {
        
        public BiduleServiceClient() {
        }
        
        public BiduleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BiduleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiduleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiduleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BiduleServoceWebClient.ServiceReference.Employee GetEmployeeDB(int Id) {
            return base.Channel.GetEmployeeDB(Id);
        }
        
        public System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.Employee> GetEmployeeDBAsync(int Id) {
            return base.Channel.GetEmployeeDBAsync(Id);
        }
        
        public void SaveEmployee(BiduleServoceWebClient.ServiceReference.Employee Employee) {
            base.Channel.SaveEmployee(Employee);
        }
        
        public System.Threading.Tasks.Task SaveEmployeeAsync(BiduleServoceWebClient.ServiceReference.Employee Employee) {
            return base.Channel.SaveEmployeeAsync(Employee);
        }
        
        public BiduleServoceWebClient.ServiceReference.Employee[] GetEmployee() {
            return base.Channel.GetEmployee();
        }
        
        public System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.Employee[]> GetEmployeeAsync() {
            return base.Channel.GetEmployeeAsync();
        }
        
        public BiduleServoceWebClient.ServiceReference.Employee GetFullTimeEmployee() {
            return base.Channel.GetFullTimeEmployee();
        }
        
        public System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.Employee> GetFullTimeEmployeeAsync() {
            return base.Channel.GetFullTimeEmployeeAsync();
        }
        
        public BiduleServoceWebClient.ServiceReference.Employee GetPartTimeEmployee() {
            return base.Channel.GetPartTimeEmployee();
        }
        
        public System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.Employee> GetPartTimeEmployeeAsync() {
            return base.Channel.GetPartTimeEmployeeAsync();
        }
        
        public string GetMessage(string nom) {
            return base.Channel.GetMessage(nom);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string nom) {
            return base.Channel.GetMessageAsync(nom);
        }
        
        public BiduleServoceWebClient.ServiceReference.Client[] GetClients() {
            return base.Channel.GetClients();
        }
        
        public System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.Client[]> GetClientsAsync() {
            return base.Channel.GetClientsAsync();
        }
        
        public BiduleServoceWebClient.ServiceReference.FullTimeClientEmployee GetEmployeeClient() {
            return base.Channel.GetEmployeeClient();
        }
        
        public System.Threading.Tasks.Task<BiduleServoceWebClient.ServiceReference.FullTimeClientEmployee> GetEmployeeClientAsync() {
            return base.Channel.GetEmployeeClientAsync();
        }
    }
}
