//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationAppMainServicesClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITrainServices")]
    public interface ITrainServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainServices/Add", ReplyAction="http://tempuri.org/ITrainServices/AddResponse")]
        int Add(int firstNumber, int secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainServices/Add", ReplyAction="http://tempuri.org/ITrainServices/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int firstNumber, int secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainServices/GetCalculations", ReplyAction="http://tempuri.org/ITrainServices/GetCalculationsResponse")]
        string[] GetCalculations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainServices/GetCalculations", ReplyAction="http://tempuri.org/ITrainServices/GetCalculationsResponse")]
        System.Threading.Tasks.Task<string[]> GetCalculationsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrainServicesChannel : LocationAppMainServicesClient.ServiceReference1.ITrainServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrainServicesClient : System.ServiceModel.ClientBase<LocationAppMainServicesClient.ServiceReference1.ITrainServices>, LocationAppMainServicesClient.ServiceReference1.ITrainServices {
        
        public TrainServicesClient() {
        }
        
        public TrainServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrainServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int firstNumber, int secondNumber) {
            return base.Channel.Add(firstNumber, secondNumber);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int firstNumber, int secondNumber) {
            return base.Channel.AddAsync(firstNumber, secondNumber);
        }
        
        public string[] GetCalculations() {
            return base.Channel.GetCalculations();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCalculationsAsync() {
            return base.Channel.GetCalculationsAsync();
        }
    }
}
