//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceEmployeeWPFClient.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        private System.DateTime DateofbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Dateofb {
            get {
                return this.DateofbField;
            }
            set {
                if ((this.DateofbField.Equals(value) != true)) {
                    this.DateofbField = value;
                    this.RaisePropertyChanged("Dateofb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private double AltitudeField;
        
        private WebServiceEmployeeWPFClient.ServiceReference.AltitudeReference AltitudeReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((this.AltitudeField.Equals(value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public WebServiceEmployeeWPFClient.ServiceReference.AltitudeReference AltitudeReference {
            get {
                return this.AltitudeReferenceField;
            }
            set {
                if ((this.AltitudeReferenceField.Equals(value) != true)) {
                    this.AltitudeReferenceField = value;
                    this.RaisePropertyChanged("AltitudeReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltitudeReference", Namespace="http://tempuri.org/")]
    public enum AltitudeReference : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ground = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ellipsoid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SeaLevel = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Surface = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.EmployeeWebServiceSoap")]
    public interface EmployeeWebServiceSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GentEmployeeDbResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GentEmployeeDb", ReplyAction="*")]
        WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbResponse GentEmployeeDb(WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GentEmployeeDb", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbResponse> GentEmployeeDbAsync(WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRadomNumber", ReplyAction="*")]
        int GetRadomNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRadomNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetRadomNumberAsync();
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetGetRadomNumberListResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGetRadomNumberList", ReplyAction="*")]
        WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListResponse GetGetRadomNumberList(WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGetRadomNumberList", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListResponse> GetGetRadomNumberListAsync(WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetTrainLocation", ReplyAction="*")]
        void SetTrainLocation(double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetTrainLocation", ReplyAction="*")]
        System.Threading.Tasks.Task SetTrainLocationAsync(double latitude, double longitude);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetTrainLocationsResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrainLocations", ReplyAction="*")]
        WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsResponse GetTrainLocations(WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrainLocations", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsResponse> GetTrainLocationsAsync(WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetRadomLocationResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRadomLocation", ReplyAction="*")]
        WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationResponse GetRadomLocation(WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRadomLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationResponse> GetRadomLocationAsync(WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GentEmployeeDbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GentEmployeeDb", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequestBody Body;
        
        public GentEmployeeDbRequest() {
        }
        
        public GentEmployeeDbRequest(WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GentEmployeeDbRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GentEmployeeDbRequestBody() {
        }
        
        public GentEmployeeDbRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GentEmployeeDbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GentEmployeeDbResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbResponseBody Body;
        
        public GentEmployeeDbResponse() {
        }
        
        public GentEmployeeDbResponse(WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GentEmployeeDbResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.Employee GentEmployeeDbResult;
        
        public GentEmployeeDbResponseBody() {
        }
        
        public GentEmployeeDbResponseBody(WebServiceEmployeeWPFClient.ServiceReference.Employee GentEmployeeDbResult) {
            this.GentEmployeeDbResult = GentEmployeeDbResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGetRadomNumberListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGetRadomNumberList", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequestBody Body;
        
        public GetGetRadomNumberListRequest() {
        }
        
        public GetGetRadomNumberListRequest(WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetGetRadomNumberListRequestBody {
        
        public GetGetRadomNumberListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGetRadomNumberListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGetRadomNumberListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListResponseBody Body;
        
        public GetGetRadomNumberListResponse() {
        }
        
        public GetGetRadomNumberListResponse(WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGetRadomNumberListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.ArrayOfString GetGetRadomNumberListResult;
        
        public GetGetRadomNumberListResponseBody() {
        }
        
        public GetGetRadomNumberListResponseBody(WebServiceEmployeeWPFClient.ServiceReference.ArrayOfString GetGetRadomNumberListResult) {
            this.GetGetRadomNumberListResult = GetGetRadomNumberListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTrainLocationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTrainLocations", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequestBody Body;
        
        public GetTrainLocationsRequest() {
        }
        
        public GetTrainLocationsRequest(WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTrainLocationsRequestBody {
        
        public GetTrainLocationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTrainLocationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTrainLocationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsResponseBody Body;
        
        public GetTrainLocationsResponse() {
        }
        
        public GetTrainLocationsResponse(WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTrainLocationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.Location[] GetTrainLocationsResult;
        
        public GetTrainLocationsResponseBody() {
        }
        
        public GetTrainLocationsResponseBody(WebServiceEmployeeWPFClient.ServiceReference.Location[] GetTrainLocationsResult) {
            this.GetTrainLocationsResult = GetTrainLocationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRadomLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRadomLocation", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequestBody Body;
        
        public GetRadomLocationRequest() {
        }
        
        public GetRadomLocationRequest(WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRadomLocationRequestBody {
        
        public GetRadomLocationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRadomLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRadomLocationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationResponseBody Body;
        
        public GetRadomLocationResponse() {
        }
        
        public GetRadomLocationResponse(WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRadomLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceEmployeeWPFClient.ServiceReference.Location GetRadomLocationResult;
        
        public GetRadomLocationResponseBody() {
        }
        
        public GetRadomLocationResponseBody(WebServiceEmployeeWPFClient.ServiceReference.Location GetRadomLocationResult) {
            this.GetRadomLocationResult = GetRadomLocationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeWebServiceSoapChannel : WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeWebServiceSoapClient : System.ServiceModel.ClientBase<WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap>, WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap {
        
        public EmployeeWebServiceSoapClient() {
        }
        
        public EmployeeWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbResponse WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap.GentEmployeeDb(WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequest request) {
            return base.Channel.GentEmployeeDb(request);
        }
        
        public WebServiceEmployeeWPFClient.ServiceReference.Employee GentEmployeeDb(int id) {
            WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequest inValue = new WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequest();
            inValue.Body = new WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequestBody();
            inValue.Body.id = id;
            WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbResponse retVal = ((WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap)(this)).GentEmployeeDb(inValue);
            return retVal.Body.GentEmployeeDbResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbResponse> WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap.GentEmployeeDbAsync(WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequest request) {
            return base.Channel.GentEmployeeDbAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbResponse> GentEmployeeDbAsync(int id) {
            WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequest inValue = new WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequest();
            inValue.Body = new WebServiceEmployeeWPFClient.ServiceReference.GentEmployeeDbRequestBody();
            inValue.Body.id = id;
            return ((WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap)(this)).GentEmployeeDbAsync(inValue);
        }
        
        public int GetRadomNumber() {
            return base.Channel.GetRadomNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetRadomNumberAsync() {
            return base.Channel.GetRadomNumberAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListResponse WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap.GetGetRadomNumberList(WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequest request) {
            return base.Channel.GetGetRadomNumberList(request);
        }
        
        public WebServiceEmployeeWPFClient.ServiceReference.ArrayOfString GetGetRadomNumberList() {
            WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequest inValue = new WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequest();
            inValue.Body = new WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequestBody();
            WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListResponse retVal = ((WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap)(this)).GetGetRadomNumberList(inValue);
            return retVal.Body.GetGetRadomNumberListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListResponse> WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap.GetGetRadomNumberListAsync(WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequest request) {
            return base.Channel.GetGetRadomNumberListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListResponse> GetGetRadomNumberListAsync() {
            WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequest inValue = new WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequest();
            inValue.Body = new WebServiceEmployeeWPFClient.ServiceReference.GetGetRadomNumberListRequestBody();
            return ((WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap)(this)).GetGetRadomNumberListAsync(inValue);
        }
        
        public void SetTrainLocation(double latitude, double longitude) {
            base.Channel.SetTrainLocation(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task SetTrainLocationAsync(double latitude, double longitude) {
            return base.Channel.SetTrainLocationAsync(latitude, longitude);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsResponse WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap.GetTrainLocations(WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequest request) {
            return base.Channel.GetTrainLocations(request);
        }
        
        public WebServiceEmployeeWPFClient.ServiceReference.Location[] GetTrainLocations() {
            WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequest inValue = new WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequest();
            inValue.Body = new WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequestBody();
            WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsResponse retVal = ((WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap)(this)).GetTrainLocations(inValue);
            return retVal.Body.GetTrainLocationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsResponse> WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap.GetTrainLocationsAsync(WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequest request) {
            return base.Channel.GetTrainLocationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsResponse> GetTrainLocationsAsync() {
            WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequest inValue = new WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequest();
            inValue.Body = new WebServiceEmployeeWPFClient.ServiceReference.GetTrainLocationsRequestBody();
            return ((WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap)(this)).GetTrainLocationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationResponse WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap.GetRadomLocation(WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequest request) {
            return base.Channel.GetRadomLocation(request);
        }
        
        public WebServiceEmployeeWPFClient.ServiceReference.Location GetRadomLocation() {
            WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequest inValue = new WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequest();
            inValue.Body = new WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequestBody();
            WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationResponse retVal = ((WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap)(this)).GetRadomLocation(inValue);
            return retVal.Body.GetRadomLocationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationResponse> WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap.GetRadomLocationAsync(WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequest request) {
            return base.Channel.GetRadomLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationResponse> GetRadomLocationAsync() {
            WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequest inValue = new WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequest();
            inValue.Body = new WebServiceEmployeeWPFClient.ServiceReference.GetRadomLocationRequestBody();
            return ((WebServiceEmployeeWPFClient.ServiceReference.EmployeeWebServiceSoap)(this)).GetRadomLocationAsync(inValue);
        }
    }
}
